//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.04 at 07:57:07 PM GFT 
//


package https.www_atlantico_com_br.celso._super.developer;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.www_atlantico_com_br.celso._super.developer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.www_atlantico_com_br.celso._super.developer
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MensagemParaTodosRequest }
     * 
     */
    public MensagemParaTodosRequest createMensagemParaTodosRequest() {
        return new MensagemParaTodosRequest();
    }

    /**
     * Create an instance of {@link MensagemParaUsuarioRequest }
     * 
     */
    public MensagemParaUsuarioRequest createMensagemParaUsuarioRequest() {
        return new MensagemParaUsuarioRequest();
    }

    /**
     * Create an instance of {@link MensagemParaUsuarioResponse }
     * 
     */
    public MensagemParaUsuarioResponse createMensagemParaUsuarioResponse() {
        return new MensagemParaUsuarioResponse();
    }

    /**
     * Create an instance of {@link MensagemParaTodosResponse }
     * 
     */
    public MensagemParaTodosResponse createMensagemParaTodosResponse() {
        return new MensagemParaTodosResponse();
    }

}
