//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.04 at 07:57:07 PM GFT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.atlantico.com.br/celso/super/developer", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.www_atlantico_com_br.celso._super.developer;
